java_binary(
    name = "candle_pipeline",
    srcs = ["CandlePipeline.java"],
    main_class = "com.verlumen.tradestar.CandlePipeline",
    deps = [
        "@maven//:org_apache_beam_beam_sdks_java_core",
    ],
)
