java_library(
    name = "candle_analyzer",
    srcs = ["CandleAnalyzer.java"],
    deps = [
        "@maven//:org_apache_beam_beam_sdks_java_core",
        "@tradestar_protos//:candles_java_proto",
        "@tradestar_protos//:strategies_java_proto",
    ],
)
