package(default_visibility = ["//:__subpackages__"])

java_binary(
    name = "beam_pipeline",
    srcs = ["BeamPipeline.java"],
    main_class = "example.BeamPipeline",
    deps = [
        "@maven//:org_apache_beam_beam_sdks_java_core",
    ],
)
