java_test(
    name = "candle_aggregator_test",
    srcs = ["CandleAggregatorTest.java"],
    deps = [
        "@maven//:org_apache_beam:beam_sdks_java_extensions_protobuf",
        "@maven//:org_apache_beam_beam_sdks_java_core",
        "@maven//:org_apache_beam_beam_sdks_java_testutils",
    ],
)
