java_binary(
    name = "candle_aggregation_pipeline",
    srcs = ["CandleAggregationPipeline.java"],
    main_class = "com.verlumen.tradestar.CandleAggregationPipeline",
    deps = [
        "@maven//:org_apache_beam_beam_sdks_java_core",
    ],
)
